[package]
authors = ["Jonathan Gao <gsmlg.com@gmail.com>"]
keywords = ["wasm", "web", "yew", "icons"]
categories = ["wasm", "web-programming", "gui"]
description = "DuskMoon Icons, a Yew icons libaray."
edition = "2021"
license = "GPL-3.0"
name = "yew-duskmoon-icons"
readme = "./README.md"
repository = "https://github.com/gsmlg-dev/yew-duskmoon-ui.git"
homepage = "https://gsmlg-dev.github.io/yew-duskmoon-ui"
version = "0.3.1"

[badges]
maintenance = { status = "actively-developed" }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
mdi = []
mdi_names = ["mdi"]
bsi = []
bsi_names = ["bsi"]
full = [
    "mdi",
    "bsi",
]
demo = [
    "mdi_names",
    "bsi_names",
]
default = ["full"]

[dependencies]
yew = { version = "0.20.0", features = ["csr"] }
implicit-clone = { version = "0.3", features = ["map"] }

